### PR TITLE
move all engines source files to one zip file

### PR DESCRIPTION
**Pull request by tico-tico**
gettin rid of one thousand unneeded files will really decrease installation time on computer systems with slow HDDs.

### CODE REVIEW

**Comment by lukasmonk** [comment]
Sorry, is a good idea but it is not the best if it is necessary to change the version of an engine, then it is necessary to update all the zip file, only for that the update is 3 mb greater.

**Comment by tico-tico** [comment]
Then maybe just delete all the sources? Why do you need them in the distribution at all?

**Comment by lukasmonk** [comment]
Because many of them are GPL and they need the sources to go with the program.
Also authors prefers that all files was included.

**Comment by tico-tico** [comment]
> Because many of them are GPL and they need the sources to go with the program.

Not really. GPL doesn't require  the sources to go with the program. The sources can be provided by request. Plenty of GPL programs distributed without sources.

> Also authors prefers that all files was included.

Now I understand. Please reject this pull request, I don't know how to do it myself.

**Comment by ddugovic** [comment]
Why not use git submodules (optional download) for the engines' source code?  Of course the author is welcome to make decisions however they want...

**Comment by lukasmonk** [comment]
Perhaps is something to think to the version 11, it will have 50 engines.

**Pull request closed without merging**
